/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence_system_project;

/**
 *
 * @author USER
 */
public class MainController extends Observer {

    private Controller controller;

    private int[] ammorArray = new int[10];
    private boolean[] positionArray = new boolean[10];

    /**
     * Creates new form MainController
     *
     * @param controller
     */
    public MainController(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dropdown = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soldierLabel = new javax.swing.JLabel();
        fuelLabel = new javax.swing.JLabel();
        ammoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        posCheck = new javax.swing.JCheckBox();
        slider = new javax.swing.JSlider();
        areaCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        newMessageTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        sendbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control Roon");

        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helicopter", "Tank", "Submarine" }));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        jButton1.setText("Collect Infomation");

        jLabel1.setText("Soldier Count");

        jLabel2.setText("Fuel Amount");

        jLabel3.setText("Ammo Amount");

        soldierLabel.setText("-");

        fuelLabel.setText("-");

        ammoLabel.setText("0");

        jLabel4.setText("Position");

        posCheck.setEnabled(false);
        posCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posCheckActionPerformed(evt);
            }
        });

        slider.setValue(0);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        areaCheck.setText("Area Clear");
        areaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaCheckActionPerformed(evt);
            }
        });

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        newMessageTextField.setText("Type here");
        newMessageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMessageTextFieldActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Everyone", "Helicopter", "Tank", "Submarine" }));

        sendbtn.setText("Send");
        sendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendbtnActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Special Notes");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soldierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fuelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ammoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(posCheck))))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newMessageTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaCheck, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sendbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(areaCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newMessageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendbtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(soldierLabel))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fuelLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ammoLabel))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(posCheck))
                        .addGap(38, 38, 38)
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        // TODO add your handling code here:
        int selectedValue = dropdown.getSelectedIndex();
        ammoLabel.setText(String.valueOf(ammorArray[selectedValue]));
        posCheck.setSelected(positionArray[selectedValue]);
    }//GEN-LAST:event_dropdownActionPerformed

    private void posCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posCheckActionPerformed

    private void newMessageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMessageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newMessageTextFieldActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        controller.setSliderValue(slider.getValue());
    }//GEN-LAST:event_sliderStateChanged

    private void sendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendbtnActionPerformed
        // TODO add your handling code here:
        if (newMessageTextField.getText().isEmpty() || newMessageTextField.getText().isBlank()) {
            return;
        }

        String selectedValue = jComboBox1.getSelectedItem().toString();
        if (selectedValue.equals("Helicopter")) {
            controller.setPrivateMessageToHelicopter("\nControl Room(c2h) : " + newMessageTextField.getText());
            messageTextArea.append("\nControl Room(c2h) : " + newMessageTextField.getText());
            newMessageTextField.setText("");
        } else if (selectedValue.equals("Everyone")) {
            controller.setMessage("\nControl Room(c2e) : " + newMessageTextField.getText());
            //messageTextArea.append("\nControl Room(c2e) : " + newMessageTextField.getText());
            newMessageTextField.setText("");
        } else if (selectedValue.equals("Tank")) {
            controller.setPrivateMessageToTank("\nControl Room(c2t) : " + newMessageTextField.getText());
            messageTextArea.append("\nControl Room(c2t) : " + newMessageTextField.getText());
            newMessageTextField.setText("");
        } else if (selectedValue.equals("Submarine")) {
            controller.setPrivateMessageToSubmarine("\nControl Room(c2s) : " + newMessageTextField.getText());
            messageTextArea.append("\nControl Room(c2s) : " + newMessageTextField.getText());
            newMessageTextField.setText("");
        }


    }//GEN-LAST:event_sendbtnActionPerformed

    private void areaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaCheckActionPerformed
        // TODO add your handling code here:
        controller.setAreaStatus(areaCheck.isSelected());
    }//GEN-LAST:event_areaCheckActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainController().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammoLabel;
    private javax.swing.JCheckBox areaCheck;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JLabel fuelLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JTextField newMessageTextField;
    private javax.swing.JCheckBox posCheck;
    private javax.swing.JButton sendbtn;
    private javax.swing.JSlider slider;
    private javax.swing.JLabel soldierLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void sendMessage(String text) {
        messageTextArea.append(text);
    }

    @Override
    public void updateHAmmor(int value) {
        ammorArray[0] = value;
        if (dropdown.getSelectedIndex() == 0) {
            ammoLabel.setText(String.valueOf(ammorArray[0]));
        }
    }

    @Override
    public void updateSAmmor(int value) {
        ammorArray[2] = value;
        if (dropdown.getSelectedIndex() == 2) {
            ammoLabel.setText(String.valueOf(ammorArray[2]));
        }
    }
    
    @Override
    public void updateTAmmor(int value){
        ammorArray[1] = value;
        if (dropdown.getSelectedIndex() == 1) {
            ammoLabel.setText(String.valueOf(ammorArray[1]));
        }
    }
    
    @Override
    public void updateHPos(boolean value){
        positionArray[0] = value;
        if (dropdown.getSelectedIndex() == 0) {
            posCheck.setSelected(positionArray[0]);
        }
    }
    
    @Override
    public void updateTPos(boolean value){
        positionArray[1] = value;
        if (dropdown.getSelectedIndex() == 1) {
            posCheck.setSelected(positionArray[1]);
        }
    }
    
    @Override
    public void updateSPos(boolean value){
        positionArray[2] = value;
        if (dropdown.getSelectedIndex() == 2) {
            posCheck.setSelected(positionArray[2]);
        }
    }
}
